name: Deploy-Models

on:
  workflow_dispatch:
    inputs:
      in_camunda_base_url:
        description: 'Camunda Base URL'
        required: true
      in_deployment_name:
        description: 'Deployment Name'
        required: false  
      in_glob_pattern:
        description: 'File Pattern'
        required: false  
      in_bpmn_folder:
        description: 'Folder containing bpmn models for deployment'
        required: false  
      in_deploy_changed_only:
        description: 'Deploy Changed only'
        required: false
        default: 'true'  

jobs:
  Deploy-Bpmn-gha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          CAMUNDA_ENDPOINT_URL: ${{ github.event.inputs.in_camunda_base_url }}
          BPMN_FILE_PATTERN: ${{ github.event.inputs.in_glob_pattern }}
          CAMUNDA_AUTH_USERNAME: ${{ secrets.CAMUNDA_API_USER }}
          CAMUNDA_AUTH_PASSWORD: ${{ secrets.CAMUNDA_API_PASSWORD }}
          CAMUNDA_AUTH_BEARER: "na"
          DEPLOYMENT_NAME: ${{ github.event.inputs.in_deployment_name }}
          CUSTOM_HTTP_HEADER_NAME : "na"
          CUSTOM_HTTP_HEADER_VALUE: "na"
          BPMN_MODEL_FOLDER: ${{ github.event.inputs.in_bpmn_folder }}
          DEPLOY_CHANGED_ONLY: ${{ github.event.inputs.in_deploy_changed_only }}
          
